{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "elastic-agent.fullname" . }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "elastic-agent.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "elastic-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
