---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bitbot.fullname" . }}
  labels:
    {{- include "bitbot.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}

