{{- if eq .Values.database.existingSecret "" -}}
apiVersion: v1
data:
{{- if .Values.database.password }}
  password: {{ .Values.database.password | b64enc }}
{{- end }}
{{- if .Values.database.root.password }}
  rootpassword: {{ .Values.database.root.password | b64enc }}
{{- end }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "fusionauth.name" . }}
    helm.sh/chart: {{ include "fusionauth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "fusionauth.database.secretName" . }}
type: Opaque
{{- end -}}