---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oragono.fullname" . }}
  labels:
    {{- include "oragono.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}

