apiVersion: v1
kind: Service
metadata:
  name: {{ include "oragono.fullname" . }}
  labels:
    {{- include "oragono.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ircd
      protocol: TCP
      name: ircd
    - port: {{ .Values.service.securePort }}
      targetPort: ircs
      protocol: TCP
      name: ircs
  selector:
    {{- include "oragono.selectorLabels" . | nindent 4 }}
