apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splashpage.fullname" . }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "splashpage.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- toYaml .Values.configMap.data | nindent 4 }}
