apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splashpage.fullname" . }}
  labels:
    {{- include "splashpage.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- toYaml .Values.configMap | nindent 4 }}
